"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireOwner } from "@/lib/auth";
import { db } from "@/lib/db";
import { propertySchema } from "@/lib/validation";
import { invitationToken, tokenHash } from "@/lib/invitations";
export async function createProperty(_: {error?:string}|undefined,formData:FormData){const {owner,user}=await requireOwner();const parsed=propertySchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Check the property details."};const property=await db.$transaction(async tx=>{const item=await tx.property.create({data:{ownerId:owner.id,...parsed.data}});await tx.activityLog.create({data:{ownerId:owner.id,actorUserId:user.id,type:"PROPERTY_CREATED",entityType:"Property",entityId:item.id,metadata:{name:item.name}}});return item});revalidatePath("/properties");redirect(`/properties/${property.id}`)}
export async function createUnit(formData:FormData){const{owner}=await requireOwner();const propertyId=String(formData.get("propertyId")??"");const property=await db.property.findFirst({where:{id:propertyId,ownerId:owner.id,archivedAt:null}});if(!property)throw new Error("Property not found");const name=String(formData.get("name")??"").trim();const rent=Number(formData.get("rent"));if(name.length<2||!Number.isFinite(rent)||rent<=0)throw new Error("Enter a valid unit name and rent");await db.unit.create({data:{propertyId,name,defaultRent:rent,status:"VACANT"}});revalidatePath(`/properties/${propertyId}`);revalidatePath("/properties")}
export async function createNotice(formData:FormData){const{owner,user}=await requireOwner();const propertyId=String(formData.get("propertyId")||"");const property=await db.property.findFirst({where:{id:propertyId,ownerId:owner.id}});if(!property)throw new Error("Property not found");const title=String(formData.get("title")||"").trim(),body=String(formData.get("body")||"").trim();if(title.length<3||body.length<5)throw new Error("Add notice details");const notice=await db.notice.create({data:{ownerId:owner.id,propertyId,title,body}});await db.activityLog.create({data:{ownerId:owner.id,actorUserId:user.id,type:"NOTICE_CREATED",entityType:"Notice",entityId:notice.id}});revalidatePath(`/properties/${propertyId}`)}
export async function createInvitation(formData:FormData){const{owner,user}=await requireOwner();const tenancyId=String(formData.get("tenancyId")||""),propertyId=String(formData.get("propertyId")||"");const tenancy=await db.tenancy.findFirst({where:{id:tenancyId,tenant:{ownerId:owner.id},unit:{propertyId}}});if(!tenancy)throw new Error("Tenancy not found");const token=invitationToken();const invitation=await db.invitation.create({data:{tenancyId,tokenHash:tokenHash(token),expiresAt:new Date(Date.now()+7*86400000)}});await db.activityLog.create({data:{ownerId:owner.id,actorUserId:user.id,type:"TENANT_INVITED",entityType:"Invitation",entityId:invitation.id}});redirect(`/properties/${propertyId}?invite=${encodeURIComponent(token)}`)}
